on:
  workflow_dispatch:
  push:
  pull_request_target:
    branches: [master]

name: Tests / test-org-mirror
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
    - name: Mirror Github to Gitee
      uses: ./.
      with:
        src: github/khadas
        dst: gitee/spectre_khadas
        dst_key: ${{ secrets.GIHUB_PUBLIC_KEY }}
        dst_token: ${{ secrets.GITEE_PRIVATE_KEY }}
        account_type: org
        force_update: true
        debug: true
        clone_style: "ssh"
